# Generated by Django 4.1.7 on 2023-03-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('stadium', models.CharField(max_length=20)),
                ('fans', models.IntegerField()),
                ('founded', models.DateField()),
            ],
        ),
    ]
